version: "3.4"

services:
  quadro-tech-back:
    image: 
    container_name: 
    hostname:
    restart: 
    networks:
      video_net:
    #    environment:
    #      - ASPNETCORE_ENVIRONMENT=docker
    healthcheck:
      test: 
      interval: 5s
      timeout: 10s
      retries: 3
    ports:
      - 93:80

  quadro-tech-mysql-prod:
    image: mysql:5.7
    hostname: 
    volumes:
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE:
    networks:
      video_net:

networks:
  video_net:
    driver: 
