version: '3.4'

services:
  quadro-tech-back-dev:
    image: 
    container_name: 
    hostname:
    restart: 
    networks:
      video_net:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=docker
    healthcheck:
     test: 
     interval: 5s
     timeout: 10s
     retries: 3
    ports:
      - 92:80

  quadro-tech-mysql-dev:
    image: 
    volumes:
    environment: 
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
    networks:
      video_net:

networks:
  video_net:
    driver: 
